//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GameServerApp.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_OPTIONS_PATHS               106
#define IDR_MAINFRAME                   128
#define IDR_THEMAPTYPE                  129
#define IDI_GAMESTATUS_NONE             130
#define IDI_GAMESTATUS_PAUSED           131
#define IDI_GAMESTATUS_UNPAUSED         132
#define IDI_TIMESLICE_ICON              134
#define IDB_USERLIST                    135
#define IDD_USER                        136
#define IDB_USER                        137
#define IDB_MAINFRAME_TB_GRAY           138
#define IDB_MAINFRAME_TB_COLOR          139
#define IDD_CIVILIZATION                140
#define IDB_CIVILIZATION                141
#define IDD_OPTIONS_NETWORK             146
#define IDD_OPTIONS_DEBUG               147
#define IDB_MAINFRAME_TB_DISABLED       148
#define IDD_OPTIONS_GAME                149
#define IDM_CIVILIZATION                151
#define IDM_USER                        152
#define IDD_SCRIPTSETMAKER              155
#define IDD_SCRIPTSETPROGRESS           156
#define IDD_SENDMESSAGE                 157
#define IDI_TRAY                        158
#define IDI_INSTRUCTIONCOUNTER_ICON     159
#define IDC_NAME                        1000
#define IDC_PASSWORD                    1001
#define IDC_PASSWORD2                   1002
#define IDC_COMMENT                     1003
#define IDC_COLOR                       1004
#define IDC_BROWSEDATA                  1008
#define IDC_BROWSEGAMETEMP              1009
#define IDC_DATA                        1010
#define IDC_GAMETEMP                    1011
#define IDC_PORT                        1011
#define IDC_ARCHIVETEMP                 1012
#define IDC_TRACE_SERVER_LOOPS          1012
#define IDC_BROWSEARCHIVETEMP           1013
#define IDC_TRACE_SERVER_CLIENT_COMMUNICATION 1013
#define IDC_TRACE_SKILL_CALLS           1014
#define IDC_TRACE_SKILLS                1015
#define IDC_TRACE_CLIENT_REQUESTS       1016
#define IDC_TRACE_INTERPRET             1017
#define IDC_TRACE_INTERPRET_DETAILS     1018
#define IDC_TRACE_NOTIFICATIONS         1019
#define IDC_DELETE_WORKING_DIRECTORY_ON_CREATE 1020
#define IDC_DELETE_WORKING_DIRECTORY_ON_DELETE 1021
#define IDC_TIMESLICE_LENGTH            1022
#define IDC_TRACE_NETWORK               1023
#define IDC_TRACE_ERROR_LOGS            1024
#define IDC_UDPALIVE                    1025
#define IDC_BROWSESOURCE                1026
#define IDC_TRACE_COMPILED_CODE         1026
#define IDC_BROWSEDESTINATION           1027
#define IDC_DESTINATION                 1028
#define IDC_SOURCE                      1029
#define IDC_PROCESS                     1030
#define IDC_ERROROUTPUT                 1034
#define IDC_STATUS                      1036
#define IDC_MESSAGE                     1037
#define IDC_GLOBALPROFILE               1038
#define IDC_LOCALPROFILE                1039
#define IDC_PROFILELIST                 1040
#define IDC_FREEZE                      1041
#define IDC_RESET                       1042
#define IDC_GLOBALCOUNT                 1042
#define IDC_SHOWPROFILING               1043
#define IDC_LOCALCOUNT                  1043
#define IDC_SHOWTRAYINFOS               1044
#define ID_GAME_PAUSE                   32771
#define ID_GAME_UNPAUSE                 32772
#define ID_GAME_STOP                    32773
#define ID_PROPERTIES                   32779
#define ID_VIEW_OPTIONS                 32780
#define ID_CIVILIZATION_ADDUSER         32782
#define ID_USER_DELETEUSER              32785
#define ID_USER_DISABLE                 32788
#define ID_USER_ENABLE                  32789
#define ID_SOUBOR_PRELOZITSKRIPTSETY    32790
#define ID_SCRIPTSET_MAKER              32791
#define ID_USER_MESSAGE                 32792
#define ID_CIVILIZATION_SENDMESSAGE     32793
#define ID_USER_SENDMESSAGE             32794
#define ID_SENDMESSAGE                  32795
#define ID_GAME_SENDMESSAGE             32796
#define ID_PROPERTIES_USER              32797
#define ID_PROPERTIES_CIVILIZATION      32798
#define ID_CIVILIZATION_RESETPROFILING  32801
#define IDS_GAMESTATUS_NONE             61204
#define IDS_GAMESTATUS_PAUSED           61205
#define IDS_GAMESTATUS_UNPAUSED         61206
#define IDS_FILE_OPENTITLE              61207
#define IDS_FILE_OPENFILTER             61208
#define IDS_FILE_THEMAPEXT              61209
#define IDS_FILE_SAVEEXT                61210
#define IDS_FILE_CANTOPENFILE           61211
#define IDS_FILE_WRONGEXTENSION         61212
#define IDS_PROGRESS_CREATEGAME         61213
#define IDS_PROGRESS_STOPGAME           61214
#define IDS_PROGRESS_LOADGAME           61215
#define IDS_PROGRESS_SAVEGAME           61216
#define IDS_PROGRESS_PAUSEGAME          61217
#define IDS_PROGRESS_UNPAUSEGAME        61218
#define IDS_USER_PASSWORDSNOTMATCH      61219
#define IDS_USER_EXISTSCOMMENT          61220
#define IDS_USER_NEWCOMMENT             61221
#define IDS_NETWORK_INITFAILED          61222
#define IDS_OPTIONSPATHS_BROWSEARCHIVETEMP_TITLE 61223
#define IDS_OPTIONSPATHS_BROWSEGAMETEMP_TITLE 61224
#define IDS_OPTIONSPATHS_BROWSEDATA_TITLE 61225
#define IDS_OPTIONS_TITLE               61226
#define IDS_FILE_SAVEFILTER             61227
#define IDS_FILE_SAVEEXTENSION          61228
#define IDS_FILE_SAVETITLE              61229
#define IDS_FILE_SAVE_OVERWRITEPROMPT   61230
#define IDS_USER_DELETECONFIRMATION     61231
#define IDS_USER_ALREADYEXISTS          61232
#define IDS_USER_DISABLECONFIRMATION    61233
#define IDS_APPLICATION_CANTOPENARCHIVETEMPDIR 61234
#define IDS_SCRIPTSETMAKER_DESTFILTER   61235
#define IDS_SCRIPTSETMAKER_DESTTITLE    61236
#define IDS_SCRIPTSETMAKER_SOURCETITLE  61237
#define IDS_SCRIPTSETPROGRESS_SUCCESS   61238
#define IDS_SCRIPTSETPROGRESS_ERROR     61239
#define IDS_FILE_THEMAPFILTER           61240
#define IDS_FILE_THEMAPFIND_TITLE       61241
#define IDS_SENDMESSAGE_USER            61242
#define IDS_SENDMESSAGE_CIVILIZATION    61243
#define IDS_FILE_BADMAP                 61244
#define IDS_SENDMESSAGE_ALL             61245
#define IDS_CREATETEMPDIRECTORYQUESTION 61246
#define IDS_CANTOVERWRITESAVEGAME       61247
#define IDS_USERLOGGEDON                61248
#define IDS_USERLOGGEDOFF               61249

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32802
#define _APS_NEXT_CONTROL_VALUE         1045
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
