#define yyFlexLexer yy2ndFlexLexer

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5



/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
class istream;

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	istream* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};


/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer



static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int CPLex2ndPass::yylex()


/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 93
#define YY_END_OF_BUFFER 94
static yyconst short int yy_acclist[351] =
    {   0,
        5,    5,   94,   92,   93,    1,   92,   93,   18,   93,
       17,   92,   93,   87,   92,   93,    9,   92,   93,   83,
       92,   93,   92,   93,   92,   93,   72,   92,   93,   73,
       92,   93,   81,   92,   93,   79,   92,   93,   88,   92,
       93,   80,   92,   93,   78,   92,   93,   82,   92,   93,
       19,   92,   93,   71,   92,   93,   70,   92,   93,   84,
       92,   93,   85,   92,   93,   86,   92,   93,   91,   92,
       93,   74,   92,   93,   89,   92,   93,   75,   92,   93,
       91,   92,   93,   91,   92,   93,   91,   92,   93,   91,
       92,   93,   91,   92,   93,   91,   92,   93,   91,   92,

       93,   91,   92,   93,   91,   92,   93,   91,   92,   93,
       91,   92,   93,   91,   92,   93,   91,   92,   93,   76,
       92,   93,   92,   93,   77,   92,   93,    5,   93,    7,
       93,    6,   93,   93,   16,   93,   11,   93,   10,   93,
       93,    1,   60,   67,   69,   65,   56,   63,   57,   64,
        3,    2,   66,   20,   19,   58,   61,   59,   62,   91,
       91,   91,   91,   91,   91,   91,   31,   91,   91,   91,
       91,   91,   91,   91,   26,   91,   39,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   68,    5,    6,    6,    8,    4,   16,   12,   13,

       12,   13,   13,   90,    2,   20,   21,   91,   91,   91,
       91,   91,   91,   91,   32,   91,   91,   91,   91,   91,
       40,   91,   91,   50,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   12,   13,
       22,   52,   91,   91,   34,   91,   53,   91,   91,   91,
       91,   91,   27,   91,   91,   91,   91,   91,   91,   49,
       91,   91,   91,   91,   91,   91,   47,   91,   54,   91,
       24,   91,   23,   91,   42,   91,   91,   12,   13,   37,
       91,   91,   91,   91,   91,   91,   55,   91,   51,   91,
       91,   91,   91,   91,   91,   48,   91,   91,   91,   30,

       91,   15,   14,   91,   91,   91,   91,   91,   91,   91,
       36,   91,   41,   91,   46,   91,   33,   91,   91,   28,
       91,   91,   91,   45,   91,   25,   91,   91,   91,   91,
       91,   38,   91,   91,   91,   91,   91,   91,   91,   43,
       91,   91,   44,   91,   91,   35,   91,   91,   29,   91
    } ;

static yyconst short int yy_accept[241] =
    {   0,
        1,    1,    1,    2,    3,    3,    3,    4,    6,    9,
       11,   14,   17,   20,   23,   25,   27,   30,   33,   36,
       39,   42,   45,   48,   51,   54,   57,   60,   63,   66,
       69,   72,   75,   78,   81,   84,   87,   90,   93,   96,
       99,  102,  105,  108,  111,  114,  117,  120,  123,  125,
      128,  130,  132,  134,  135,  137,  139,  141,  142,  143,
      144,  145,  146,  146,  147,  148,  149,  150,  151,  152,
      153,  154,  155,  156,  156,  157,  158,  159,  160,  161,
      162,  163,  164,  165,  166,  167,  169,  170,  171,  172,
      173,  174,  175,  177,  179,  180,  181,  182,  183,  184,

      185,  186,  187,  188,  189,  190,  191,  192,  193,  194,
      195,  196,  197,  198,  199,  201,  203,  204,  205,  206,
      207,  207,  207,  208,  209,  210,  211,  212,  213,  214,
      215,  217,  218,  219,  220,  221,  223,  224,  226,  227,
      228,  229,  230,  231,  232,  233,  234,  235,  236,  237,
      238,  239,  241,  241,  241,  242,  244,  245,  247,  249,
      250,  251,  252,  253,  255,  256,  257,  258,  259,  260,
      262,  263,  264,  265,  266,  267,  269,  271,  273,  275,
      277,  278,  280,  280,  280,  282,  283,  284,  285,  286,
      287,  289,  291,  292,  293,  294,  295,  296,  298,  299,

      300,  302,  303,  304,  305,  306,  307,  308,  309,  310,
      311,  313,  315,  317,  319,  320,  322,  323,  324,  326,
      328,  329,  330,  331,  332,  334,  335,  336,  337,  338,
      339,  340,  342,  343,  345,  346,  348,  349,  351,  351
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   26,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   29,   28,   28,
       30,   31,   32,    1,   28,    1,   33,   34,   35,   36,

       37,   38,   28,   39,   40,   28,   41,   42,   43,   44,
       45,   46,   28,   47,   48,   49,   50,   51,   52,   53,
       28,   28,   54,   55,   56,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[57] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    4,    5,    5,    5,
        1,    1,    1,    1,    1,    5,    5,    6,    6,    1,
        3,    1,    5,    5,    5,    5,    5,    5,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    1,    1,    1
    } ;

static yyconst short int yy_base[251] =
    {   0,
        0,    0,   54,   55,   56,   57,  353,  354,  350,  354,
      354,  327,  354,  326,  341,    0,  354,  354,  324,   51,
      354,   46,  354,   56,   58,  354,  354,   66,  323,  322,
        0,  354,  354,  354,   37,   53,   46,   47,   60,   59,
       49,  308,   64,   65,  300,  298,   76,  354,  287,  354,
        0,  354,   94,  329,    0,  354,  354,   99,  338,  354,
      354,  354,  330,  354,  354,  354,  354,  354,  354,    0,
      354,  102,  107,  117,  354,  354,  354,  354,    0,  293,
      300,  288,  302,   64,  296,    0,  287,  284,  282,  288,
      284,  281,    0,   92,  278,  284,  276,  280,  276,  276,

      281,  280,  269,  278,  277,  276,  275,  354,    0,  116,
      126,  354,  354,    0,  127,  130,  133,  354,    0,  139,
      149,  152,  155,  272,  280,  275,  264,  267,  106,  276,
        0,  271,  270,  258,  272,    0,  255,    0,  263,  260,
      251,  264,  249,  261,  248,  248,  258,  245,  257,  243,
      249,  159,  163,  166,  173,    0,  249,    0,    0,  256,
      239,  247,  236,    0,  241,  247,  234,  249,  243,    0,
      233,  230,  243,  230,  241,    0,    0,    0,    0,  237,
      237,  184,    0,    0,    0,  229,  225,  227,  228,  233,
        0,    0,  224,  227,  222,  220,  215,    0,  224,  222,

        0,  354,  354,  225,  209,  194,  190,  190,  197,  193,
        0,    0,    0,    0,  179,    0,  183,  158,    0,    0,
      157,  155,  139,  116,    0,  118,  112,  111,   97,   93,
       84,    0,   63,    0,   34,    0,   25,    0,  354,  204,
      210,  216,  218,  224,  230,  236,  242,  248,  254,   60
    } ;

static yyconst short int yy_def[251] =
    {   0,
      239,    1,  240,  240,  241,  241,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  242,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      243,  239,  239,  239,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  239,  239,  239,
      244,  239,  245,  239,  246,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  247,
      239,  239,  239,  239,  239,  239,  239,  239,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,

      243,  243,  243,  243,  243,  243,  243,  239,  244,  245,
      245,  239,  239,  246,  239,  239,  239,  239,  247,  239,
      239,  239,  239,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  239,  248,  239,  239,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  239,  249,  250,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,

      243,  239,  239,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,    0,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239
    } ;

static yyconst short int yy_nxt[411] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   25,   25,
       26,   27,   28,   29,   30,   31,   31,   31,   31,   32,
       33,   34,   31,   35,   36,   37,   38,   39,   31,   40,
       31,   31,   31,   41,   31,   31,   42,   43,   44,   45,
       46,   47,   31,   48,   49,   50,   52,   52,   56,   56,
       67,   57,   57,   65,  203,   53,   53,   69,  238,   68,
       54,   54,   70,   72,   66,   73,   73,   73,  237,   71,
       75,   80,   85,   81,   74,   82,   58,   58,   88,   76,
       86,   83,   90,   95,   74,   87,   93,   84,   96,   89,

       98,   91,   94,  102,   92,  111,  128,  129,  106,  236,
      112,  103,   99,  100,  107,  101,  115,  116,  117,  120,
      120,  120,   72,  235,   73,   73,   73,  239,  121,  122,
      234,  122,  239,   74,  123,  123,  123,  111,  121,  137,
      138,  233,  112,   74,  152,  152,  117,  152,  152,  117,
      117,  117,  117,  161,  162,  153,  120,  120,  120,  232,
      231,  154,  230,  154,  229,  121,  155,  155,  155,  123,
      123,  123,  123,  123,  123,  121,  182,  182,  117,  153,
      184,  184,  184,  155,  155,  155,  228,  227,  184,  184,
      155,  155,  155,  226,  225,  184,  184,  184,  184,  184,

      184,  117,  117,  117,   51,   51,   51,   51,   51,   51,
       55,   55,   55,   55,   55,   55,   63,  224,   63,   63,
       63,   63,   79,   79,  109,  223,  109,  222,  109,  109,
      110,  221,  110,  110,  110,  110,  114,  220,  219,  114,
      114,  114,  119,  218,  119,  119,  119,  119,  183,  183,
      183,  183,  183,  183,  202,  202,  202,  202,  217,  202,
      216,  215,  214,  213,  212,  211,  210,  209,  208,  207,
      206,  205,  204,  201,  200,  199,  198,  197,  196,  195,
      194,  193,  192,  191,  190,  189,  188,  187,  186,  185,
      181,  180,  179,  178,  177,  176,  175,  174,  173,  172,

      171,  170,  169,  168,  167,  166,  165,  164,  163,  160,
      159,  158,  157,  156,  151,  150,  149,  148,  147,  146,
      145,  144,  143,  142,  141,  140,  139,  136,  135,  134,
      133,  132,  131,  130,  127,  126,  125,  124,  118,   59,
      113,  108,  105,  104,   97,   78,   77,   64,   62,   61,
       60,   59,  239,    7,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,

      239,  239,  239,  239,  239,  239,  239,  239,  239,  239
    } ;

static yyconst short int yy_chk[411] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,    5,    6,
       22,    5,    6,   20,  250,    3,    4,   24,  237,   22,
        3,    4,   24,   25,   20,   25,   25,   25,  235,   24,
       28,   35,   37,   35,   25,   36,    5,    6,   38,   28,
       37,   36,   39,   41,   25,   37,   40,   36,   41,   38,

       43,   39,   40,   44,   39,   53,   84,   84,   47,  233,
       53,   44,   43,   43,   47,   43,   58,   58,   58,   72,
       72,   72,   73,  231,   73,   73,   73,  110,   72,   74,
      230,   74,  110,   73,   74,   74,   74,  111,   72,   94,
       94,  229,  111,   73,  115,  115,  115,  116,  116,  116,
      117,  117,  117,  129,  129,  115,  120,  120,  120,  228,
      227,  121,  226,  121,  224,  120,  121,  121,  121,  122,
      122,  122,  123,  123,  123,  120,  152,  152,  152,  115,
      153,  153,  153,  154,  154,  154,  223,  222,  153,  153,
      155,  155,  155,  221,  218,  153,  153,  153,  153,  153,

      153,  182,  182,  182,  240,  240,  240,  240,  240,  240,
      241,  241,  241,  241,  241,  241,  242,  217,  242,  242,
      242,  242,  243,  243,  244,  215,  244,  210,  244,  244,
      245,  209,  245,  245,  245,  245,  246,  208,  207,  246,
      246,  246,  247,  206,  247,  247,  247,  247,  248,  248,
      248,  248,  248,  248,  249,  249,  249,  249,  205,  249,
      204,  200,  199,  197,  196,  195,  194,  193,  190,  189,
      188,  187,  186,  181,  180,  175,  174,  173,  172,  171,
      169,  168,  167,  166,  165,  163,  162,  161,  160,  157,
      151,  150,  149,  148,  147,  146,  145,  144,  143,  142,

      141,  140,  139,  137,  135,  134,  133,  132,  130,  128,
      127,  126,  125,  124,  107,  106,  105,  104,  103,  102,
      101,  100,   99,   98,   97,   96,   95,   92,   91,   90,
       89,   88,   87,   85,   83,   82,   81,   80,   63,   59,
       54,   49,   46,   45,   42,   30,   29,   19,   15,   14,
       12,    9,    7,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,

      239,  239,  239,  239,  239,  239,  239,  239,  239,  239
    } ;

#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#define INITIAL 0
/* Lexikalni 'gramatika' pro cteni konfiguracnich souboru */
#define YY_NEVER_INTERACTIVE 1
/************************************************************
 *
 * Projekt: Strategicka hra
 *    Cast: Prekladac
 *   Autor: Helena Kupková
 *  
 *   Popis: Gramatika, z niz bude lexem vygenerovan automat
 * 
 ***********************************************************/

class CObject;

#define YYSTYPE CPExpr

#include "stdafx.h"
#include "CompilerKernel.h"
#include "PLex2ndPass.h"
#include "Syntax.h"

extern int yydebug;

#define YY_SKIP_YYWRAP

/* exclusive start conditions */
#define COMMENT 1

#define STRING 2

/* definitions */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif


#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yyFlexLexer::yylex()
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;



    /* RULES */


	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = &cin;

		if ( ! yyout )
			yyout = &cout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 240 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 354 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
//find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
/* empty - whitespace */
	YY_BREAK
case 2:
YY_RULE_SETUP
/* empty - one line comment */
	YY_BREAK
case 3:
YY_RULE_SETUP
{  /* multiline comment */
			m_nCommentLevel=1;
            BEGIN(COMMENT);
		}
	YY_BREAK

case 4:
YY_RULE_SETUP
m_nCommentLevel++;
	YY_BREAK
case 5:
YY_RULE_SETUP
/* empty - anything but a '*' or '/n' or '/' */
	YY_BREAK
case 6:
YY_RULE_SETUP
/* empty - '*' and anything but '*' and '/' */
	YY_BREAK
case 7:
YY_RULE_SETUP
/* empty */
	YY_BREAK
case 8:
YY_RULE_SETUP
{
					m_nCommentLevel--;
					if (m_nCommentLevel==0) BEGIN(INITIAL);
				}
	YY_BREAK

case 9:
YY_RULE_SETUP
{
			BEGIN(STRING); /* string */
			m_strString.Empty();
		}
	YY_BREAK

case 10:
YY_RULE_SETUP
{
                BEGIN(INITIAL); 
				m_pExpr->SetConstant((LPCTSTR)m_strString, m_pCompilerKrnl);
                return LITERAL_STRING;
            }
	YY_BREAK
case 11:
YY_RULE_SETUP
{	/* EOL in string */ 
				m_pCompilerKrnl->ErrorMessage("unterminated string constant");
                return 0;
			}
	YY_BREAK
case 12:
YY_RULE_SETUP
{	/* octal excape sequence */
					sscanf(yytext+1, "%o", &m_nInt);
					if (m_nInt>0xff) m_pCompilerKrnl->ErrorMessage("octal constant is out-of-bounds");
					m_strString+=yytext;
				}
	YY_BREAK
case 13:
YY_RULE_SETUP
{ 	/* bad octal escape sequence */
					m_pCompilerKrnl->ErrorMessage("bad escape sequence");						
					m_strString+=yytext;
				}
	YY_BREAK
case 14:
YY_RULE_SETUP
{ 	/* hexadecimal excape sequence */ 
							m_strString+=yytext;
                        }
	YY_BREAK
case 15:
YY_RULE_SETUP
{   /* bad hexadecimal excape sequence */
							m_pCompilerKrnl->ErrorMessage("bad escape sequence");						
							m_strString+=yytext;
					    }
	YY_BREAK
case 16:
YY_RULE_SETUP
m_strString+=yytext;
	YY_BREAK

case 17:
YY_RULE_SETUP
/* empty */
	YY_BREAK
case 18:
YY_RULE_SETUP
{
#ifdef _DEBUG
					if (yydebug) m_pCompilerKrnl->Pause();					
#endif
				}
	YY_BREAK
case 19:
YY_RULE_SETUP
{
					m_pExpr->SetConstant(atoi(yytext), m_pCompilerKrnl);
					return LITERAL_INT;
				}
	YY_BREAK
case 20:
YY_RULE_SETUP
{
							m_pExpr->SetConstant((float)atof(yytext), m_pCompilerKrnl);
							return LITERAL_FLOAT;
						}
	YY_BREAK
case 21:
YY_RULE_SETUP
{
							m_pExpr->SetConstant((float)atof(yytext), m_pCompilerKrnl);
							return LITERAL_FLOAT;
						}
	YY_BREAK
case 22:
YY_RULE_SETUP
{
										m_pExpr->SetConstant((float)atof(yytext), m_pCompilerKrnl);
										return LITERAL_FLOAT;
									}
	YY_BREAK
case 23:
YY_RULE_SETUP
{
				m_pExpr->SetType(T_VOID, m_pCompilerKrnl);
				return VOID_TYPE;
			}
	YY_BREAK
case 24:
YY_RULE_SETUP
return UNIT;
	YY_BREAK
case 25:
YY_RULE_SETUP
return EXTENDS;
	YY_BREAK
case 26:
YY_RULE_SETUP
return IF;
	YY_BREAK
case 27:
YY_RULE_SETUP
return ELSE;
	YY_BREAK
case 28:
YY_RULE_SETUP
return COMMAND;
	YY_BREAK
case 29:
YY_RULE_SETUP
return NOTIFICATION;
	YY_BREAK
case 30:
YY_RULE_SETUP
return WHILE;
	YY_BREAK
case 31:
YY_RULE_SETUP
return DO;
	YY_BREAK
case 32:
YY_RULE_SETUP
return DUP;
	YY_BREAK
case 33:
YY_RULE_SETUP
return SWITCH;
	YY_BREAK
case 34:
YY_RULE_SETUP
return CASE;	
	YY_BREAK
case 35:
YY_RULE_SETUP
return CONSTRUCTOR;
	YY_BREAK
/*destructor	return DESTRUCTOR;*/
case 36:
YY_RULE_SETUP
return RETURN;
	YY_BREAK
case 37:
YY_RULE_SETUP
return BREAK;
	YY_BREAK
case 38:
YY_RULE_SETUP
return CONTINUE;
	YY_BREAK
case 39:
YY_RULE_SETUP
return IN_KWD;
	YY_BREAK
case 40:
YY_RULE_SETUP
return FOR;
	YY_BREAK
case 41:
YY_RULE_SETUP
return SENDTO;
	YY_BREAK
case 42:
YY_RULE_SETUP
return WAIT;
	YY_BREAK
case 43:
YY_RULE_SETUP
return WAITFIRST;
	YY_BREAK
case 44:
YY_RULE_SETUP
return INSTANCEOF_TOKEN;
	YY_BREAK
case 45:
YY_RULE_SETUP
return DEFAULT;
	YY_BREAK
/*try			return TRY_TOKEN;*/
/*catch		return CATCH_TOKEN;  */
case 46:
YY_RULE_SETUP
return STRUCT;
	YY_BREAK
case 47:
YY_RULE_SETUP
return THIS_KWD;
	YY_BREAK
case 48:
YY_RULE_SETUP
return SUPER;
	YY_BREAK
case 49:
YY_RULE_SETUP
{
                m_pExpr->SetConstant((int)0, m_pCompilerKrnl);
				return LITERAL_INT;
            }
	YY_BREAK
case 50:
YY_RULE_SETUP
{
				m_pExpr->SetType(T_INT, m_pCompilerKrnl);
				return TYPE_INT;
			}
	YY_BREAK
case 51:
YY_RULE_SETUP
{
				m_pExpr->SetType(T_FLOAT, m_pCompilerKrnl);
				return TYPE_FLOAT;
			}
	YY_BREAK
case 52:
YY_RULE_SETUP
{
				m_pExpr->SetType(T_BOOL, m_pCompilerKrnl);
				return TYPE_BOOL;	
			}
	YY_BREAK
case 53:
YY_RULE_SETUP
{
				m_pExpr->SetType(T_CHAR, m_pCompilerKrnl);
				return TYPE_CHAR;
			}
	YY_BREAK
case 54:
YY_RULE_SETUP
{
			m_pExpr->SetConstant(true, m_pCompilerKrnl);
			return LITERAL_BOOL;
		}
	YY_BREAK
case 55:
YY_RULE_SETUP
{	
			m_pExpr->SetConstant(false, m_pCompilerKrnl);
			return LITERAL_BOOL;
		}
	YY_BREAK
case 56:
YY_RULE_SETUP
return PLUSPLUS;
	YY_BREAK
case 57:
YY_RULE_SETUP
return MINUSMINUS;
	YY_BREAK
case 58:
YY_RULE_SETUP
return BACKARROW;
	YY_BREAK
case 59:
YY_RULE_SETUP
return EQ;
	YY_BREAK
case 60:
YY_RULE_SETUP
return NEQ;
	YY_BREAK
case 61:
YY_RULE_SETUP
return LEQ;
	YY_BREAK
case 62:
YY_RULE_SETUP
return GEQ;
	YY_BREAK
case 63:
YY_RULE_SETUP
return PLUSASS;
	YY_BREAK
case 64:
YY_RULE_SETUP
return MINUSASS;
	YY_BREAK
case 65:
YY_RULE_SETUP
return MULTASS;
	YY_BREAK
case 66:
YY_RULE_SETUP
return DIVASS;
	YY_BREAK
case 67:
YY_RULE_SETUP
return MODASS;
	YY_BREAK
case 68:
YY_RULE_SETUP
return OR;
	YY_BREAK
case 69:
YY_RULE_SETUP
return AND;    
	YY_BREAK
case 70:
case 71:
case 72:
case 73:
case 74:
case 75:
case 76:
case 77:
case 78:
case 79:
case 80:
case 81:
case 82:
case 83:
case 84:
case 85:
case 86:
case 87:
case 88:
YY_RULE_SETUP
{
            m_pExpr->SetConstant(yytext[0], m_pCompilerKrnl);
            return yytext[0];
        }
	YY_BREAK
case 89:
YY_RULE_SETUP
{
            m_pExpr->SetConstant(yytext[0], m_pCompilerKrnl);
            return yytext[0];
        }
	YY_BREAK
case 90:
YY_RULE_SETUP
{
			m_pExpr->SetConstant(yytext[1], m_pCompilerKrnl);
			return LITERAL_CHAR;
		}
	YY_BREAK
case 91:
YY_RULE_SETUP
{
								m_pExpr->SetDeclar(CString(yytext), m_pCompilerKrnl);
								return IDENTIFIER;
							}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(STRING):
{ 

#ifdef _DEBUG
				if (yydebug) m_pCompilerKrnl->Pause();					
#endif
				return 0; 
            }
	YY_BREAK
case 92:
YY_RULE_SETUP
m_pCompilerKrnl->ErrorMessage("unexpected character (%c - 0x%02X)",yytext[0],yytext[0]);
	YY_BREAK
case 93:
YY_RULE_SETUP
ECHO;
	YY_BREAK

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */

yyFlexLexer::yyFlexLexer( istream* arg_yyin, ostream* arg_yyout )
	{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 1;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = 0;

	yy_current_buffer = 0;

#ifdef YY_USES_REJECT
	yy_state_buf = new yy_state_type[YY_BUF_SIZE + 2];
#else
	yy_state_buf = 0;
#endif
	}

yyFlexLexer::~yyFlexLexer()
	{
	delete yy_state_buf;
	yy_delete_buffer( yy_current_buffer );
	}

void yyFlexLexer::switch_streams( istream* new_in, ostream* new_out )
	{
	if ( new_in )
		{
		yy_delete_buffer( yy_current_buffer );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE ) );
		}

	if ( new_out )
		yyout = new_out;
	}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
	{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
	}

void yyFlexLexer::LexerOutput( const char* buf, int size )
	{
	(void) yyout->write( buf, size );
	}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

int yyFlexLexer::yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

yy_state_type yyFlexLexer::yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 240 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 240 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 239);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


void yyFlexLexer::yyunput( int c, register char* yy_bp )
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}


int yyFlexLexer::yyinput()
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


void yyFlexLexer::yyrestart( istream* input_file )
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


void yyFlexLexer::yy_load_buffer_state()
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( istream* file, int size )
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


extern "C" int isatty YY_PROTO(( int ));
void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, istream* file )

	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

	b->yy_is_interactive = 0;
	}


void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#endif


#ifndef YY_NO_SCAN_STRING
#endif


#ifndef YY_NO_SCAN_BYTES
#endif


#ifndef YY_NO_PUSH_STATE
void yyFlexLexer::yy_push_state( int new_state )
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
void yyFlexLexer::yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
int yyFlexLexer::yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif


void yyFlexLexer::LexerError( yyconst char msg[] )
	{
	cerr << msg << '\n';
	exit( YY_EXIT_FAILURE );
	}


/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
