//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MapEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MAPEDTYPE                   129
#define IDD_SPLASHWINDOW                130
#define IDD_MAPEXEDITOR                 131
#define IDD_MAPPROPERTIES               133
#define IDD_MAPEXLIBRARYEDITOR          134
#define IDD_EDITLIBRARY                 136
#define IDD_DELETELIBRARY               137
#define IDD_MAPEX                       138
#define IDD_MAPEXSIZE                   139
#define IDB_MAPEXEDITTB                 142
#define IDI_MAPEX                       143
#define IDD_LANDTYPESELECT              146
#define IDM_VIEWGRAPHICSMENU            149
#define IDD_NEWMAP                      150
#define IDR_MAPEXBAR                    152
#define IDD_SELECTMAPEX                 156
#define IDD_DIALOG1                     157
#define IDC_MOVECURSOR                  158
#define IDI_DRAWICON                    159
#define IDI_SELECTIONICON               160
#define IDM_GRIDSIZEMENU                161
#define IDC_SELECTIONCURSOR             164
#define IDD_CIVILIZATION                165
#define IDD_CIVILIZATIONEDITOR          166
#define IDD_UNITAPPEARANCE              167
#define IDD_UNITMAINPAGE                168
#define IDD_UNITLIBRARIES               169
#define IDD_DELETEUNITLIBRARY           170
#define IDD_EDITUNITLIBRARY             171
#define IDD_UNITLIBRARYEDITOR           172
#define IDD_UNITAPPEARANCEPAGE          173
#define IDD_UNITLANDTYPESPAGE           174
#define IDD_UNITMODESPAGE               175
#define IDB_ULTCHECKIMAGELIST           176
#define IDD_UNITSKILLSPAGE              177
#define IDD_NEWSKILLTYPE                178
#define IDB_USMCHECKIMAGELIST           179
#define IDD_EXAMPLESKILLTYPE            180
#define IDR_UNITBAR                     183
#define IDD_SELECTUNIT                  185
#define IDD_FINISH_PROGRESS             186
#define IDD_MOVESKILL                   187
#define IDD_RESOURCES                   188
#define IDD_EDITRESOURCES               189
#define IDD_STARTDLG                    191
#define IDD_INVISIBILITY                192
#define IDD_EDITINVISIBILITY            193
#define IDB_VISCHECKIMAGELIST           194
#define IDB_TOOLBAR_COLOR               195
#define IDB_TOOLBAR_GRAY                196
#define IDB_TOOLBAR_DISABLE             197
#define IDD_SCRIPTSETEDIT               198
#define IDD_SCRIPTSET                   199
#define IDD_BULLETATTACKSKILL           200
#define IDD_BULLETDEFENSESKILL          201
#define IDD_MAKESKILL                   202
#define IDD_MAKESKILLTYPE               204
#define IDD_FINDPATHGRAPHS              205
#define IDD_FINDPATHGRAPHEDIT           206
#define IDD_MINESKILL                   207
#define IDD_RESOURCESKILL               208
#define IDD_STORAGESKILL                209
#define IDB_KRYSTAL2                    214
#define IDB_KRYSTAL                     215
#define IDB_KRYSTAL3                    216
#define IDD_SETMAPSIZE                  217
#define IDC_LIBRARYCOMBO                1004
#define IDC_ADDMAPEX                    1006
#define IDC_DELETEMAPEX                 1007
#define IDC_EDITMAPEX                   1008
#define IDC_MAPEXPREVIEW                1010
#define IDC_FILENAME                    1011
#define IDC_MAPNAME                     1012
#define IDC_MAPDESCRIPTION              1013
#define IDC_NAME                        1015
#define IDC_EDIT                        1017
#define IDC_LIST                        1018
#define IDC_DELETE                      1019
#define IDC_MAPEXLIST                   1020
#define IDC_UP                          1020
#define IDC_DOWN                        1021
#define IDC_VIEW                        1026
#define IDC_WIDTH                       1027
#define IDC_HEIGHT                      1028
#define IDC_TOOLBAR                     1029
#define IDC_SPLASHBITMAP                1031
#define IDC_DESCRIPTION                 1035
#define IDC_MAPEXLISTCTRL               1038
#define IDC_LANDTYPELIST                1040
#define IDC_COLOR                       1043
#define IDC_ADD                         1045
#define IDC_NORTHWEST                   1047
#define IDC_NORTH                       1048
#define IDC_NORTHEAST                   1049
#define IDC_UNITLISTCTRL                1049
#define IDC_WEST                        1050
#define IDC_ADDUNIT                     1050
#define IDC_SOUTHWEST                   1051
#define IDC_DELETEUNIT                  1051
#define IDC_SOUTH                       1052
#define IDC_EDITUNIT                    1052
#define IDC_SOUTHEAST                   1053
#define IDC_UNITPREVIEW                 1053
#define IDC_EAST                        1054
#define IDC_LIFEMAX                     1058
#define IDC_VIEWRADIUS                  1059
#define IDC_MODES                       1062
#define IDC_MODE                        1070
#define IDC_APPEARANCE                  1072
#define IDC_APPEARANCE1                 1073
#define IDC_MOVEWIDTH                   1074
#define IDC_APPEARANCEMINE1             1074
#define IDC_APPEARANCE2                 1075
#define IDC_APPEARANCEMINE2             1076
#define IDC_APPEARANCE3                 1077
#define IDC_APPEARANCEMINE3             1078
#define IDC_MODELIST                    1079
#define IDC_ENABLED                     1081
#define IDC_EDIT1                       1082
#define IDC_CIVCOMBO                    1083
#define IDC_ABSOLUTE                    1083
#define IDC_EDIT4                       1083
#define IDC_UNLOAD_DISTANCE             1083
#define IDC_UNITLIST                    1084
#define IDC_MAPEXSIZE                   1085
#define IDC_PROCESSING                  1086
#define IDC_PROGRESS                    1087
#define IDC_SCRIPTSET                   1088
#define IDC_SPEED                       1089
#define IDC_RESOURCES                   1090
#define IDC_SETIMAGE                    1091
#define IDC_RESOURCES2                  1091
#define IDC_MINE_RESOURCES              1091
#define IDC_PREVIEW                     1092
#define IDC_RESOURCES3                  1092
#define IDC_UNLOAD_RESOURCES            1092
#define IDC_SELECTABLE                  1095
#define IDC_ZPOS                        1097
#define IDC_NEWMAP                      1098
#define IDC_LASTOPENED                  1099
#define IDC_LASTOPENEDMAP               1100
#define IDC_OPEN                        1101
#define IDC_INVISIBILITY                1102
#define IDC_DETECTION                   1103
#define IDC_MOVEAPPEARANCE              1104
#define IDC_PATH                        1110
#define IDC_BROWSE                      1112
#define IDC_PERIOD                      1113
#define IDC_INTENSITY                   1114
#define IDC_OFFSET                      1116
#define IDC_LENGTH                      1117
#define IDC_LOADTIME                    1118
#define IDC_RADIUS                      1121
#define IDC_ALTITUDEMIN                 1122
#define IDC_ALTITUDEMAX                 1123
#define IDC_LINEAR                      1124
#define IDC_UNITTYPELIST                1125
#define IDC_ADDUNITTYPE                 1127
#define IDC_REMOVEUNITTYPE              1128
#define IDC_EDITUNITTYPE                1129
#define IDC_UNITTYPE                    1133
#define IDC_TIMETOMAKE                  1134
#define IDC_STARTPOS                    1139
#define IDC_COMBO1                      1140
#define IDC_APPEARANCE_BEFORE_MINE      1140
#define IDC_EDIT2                       1141
#define IDC_TIMESLICES_BEFORE_MINE      1141
#define IDC_COMBO2                      1142
#define IDC_APPEARANCE_MINE             1142
#define IDC_COMBO3                      1143
#define IDC_APPEARANCE_AFTER_MINE       1143
#define IDC_EDIT3                       1144
#define IDC_TIMESLICES_AFTER_MINE       1144
#define IDC_COMBO4                      1145
#define IDC_APPEARANCE_BEFORE_UNLOAD    1145
#define IDC_EDIT5                       1146
#define IDC_TIMESLICES_BEFORE_UNLOAD    1146
#define IDC_COMBO5                      1147
#define IDC_APPEARANCE_UNLOAD           1147
#define IDC_COMBO6                      1148
#define IDC_APPEARANCE_AFTER_UNLOAD     1148
#define IDC_EDIT6                       1149
#define IDC_TIMESLICES_AFTER_UNLOAD     1149
#define IDC_APPEARANCE_BEFORE_MINE_FULL 1150
#define IDC_TIMESLICES_BEFORE_MINE_FULL 1151
#define IDC_INITRESOURCES               1152
#define IDC_APPEARANCE_MINE_FULL        1152
#define IDC_TSRESOURCES                 1153
#define IDC_STORAGE_RESOURCES           1154
#define IDC_RESOURCESLIMIT1             1154
#define IDC_MINE_DISTANCE               1155
#define IDC_RESOURCESLIMIT2             1155
#define IDC_RESOURCESLIMIT3             1156
#define IDC_LOADED_MODE                 1156
#define IDC_LIFEBAR_HIDE                1158
#define IDC_LIFEBAR_SELECTED            1159
#define IDC_LIFEBAR_SHOW                1160
#define IDC_APPEARANCE_AFTER_UNLOAD_FULL 1160
#define IDC_TIMESLICES_AFTER_UNLOAD_FULL 1161
#define ID_MAPEXEDITOR                  32771
#define ID_MAPEX_NOVKNIHOVNA            32772
#define ID_FILE_PROPERTIES              32773
#define ID_MAPEX_NEWLIBRARY             32774
#define ID_MAPEX_OPENLIBRARY            32775
#define ID_MAPEX_DELETELIBRARY          32776
#define ID_MAPEX_EDITLIBRARY            32777
#define ID_FILE_SETLANDTYPES            32780
#define ID_MAPEXGRP_GRAPHICS            32781
#define ID_MAPEXGRP_GRID                32782
#define ID_MAPEXGRP_BOTH                32783
#define ID_MAPEXBUT                     32784
#define ID_VIEW_BL2                     32796
#define ID_VIEW_BL3                     32797
#define ID_VIEW_UL                      32798
#define ID_VIEW_BL1                     32799
#define ID_SELECT_BL1                   32800
#define ID_SELECT_BL2                   32801
#define ID_SELECT_BL3                   32802
#define ID_SELECT_UL                    32803
#define ID_MAPEX_DELETE                 32815
#define ID_MAP_GRID                     32816
#define ID_GRIDSIZE_1                   32817
#define ID_GRIDSIZE_2                   32818
#define ID_GRIDSIZE_4                   32819
#define ID_GRIDSIZE_8                   32820
#define ID_GRIDSIZE_16                  32821
#define ID_MAP_LANDTYPES                32822
#define ID_VIEW_MINIMAP                 32824
#define ID_VIEW_MAPEXBAR                32826
#define ID_MINIMAP_ZOOMIN               32827
#define ID_MINIMAP_ZOOMOUT              32828
#define ID_MAPEX_ZPOS                   32833
#define ID_UNIT_CIVILIZATIONS           32834
#define ID_UNIT_NEWLIBRARY              32835
#define ID_UNIT_OPENLIBRARY             32836
#define ID_UNIT_EDITLIBRARY             32837
#define ID_UNIT_DELETELIBRARY           32838
#define ID_UNIT_EDITOR                  32839
#define ID_UNITBUT                      32840
#define ID_FILE_REBUILDLIBRARIES        32845
#define ID_FILE_FINISH                  32846
#define ID_VIEW_UNITBAR                 32847
#define ID_UNIT_DIRECTION_LEFT          32849
#define ID_UNIT_DIRECTION_RIGHT         32851
#define ID_UNIT_DIRECTION_RANDOM        32852
#define ID_FILE_RESOURCES               32853
#define ID_MAPEX_UP                     32854
#define ID_MAPEX_DOWN                   32855
#define ID_FILE_INVISIBILITY            32856
#define ID_FILE_FINISHEXIT              32857
#define ID_FILE_SCRIPTSET               32858
#define ID_FILE_FINDPATHGRAPHS          32859
#define ID_FILE_SETMAPSIZE              32860
#define IDS_SPLASHBITMAP                61204
#define IDS_REALLYRESIZEMAP             61205

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        218
#define _APS_NEXT_COMMAND_VALUE         32861
#define _APS_NEXT_CONTROL_VALUE         1161
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
